version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: genderforcare
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
